---
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/tomato_field/model/igus_rebel/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/oakd_link/rgbd_camera/camera_info"
  gz_topic_name: "/world/tomato_field/model/igus_rebel/link/link_8/sensor/depth_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS  
- ros_topic_name: "/oakd_link/rgbd_camera/depth_image"
  gz_topic_name: "/world/tomato_field/model/igus_rebel/link/link_8/sensor/depth_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/oakd_link/rgbd_camera/image_raw"
  gz_topic_name: "/world/tomato_field/model/igus_rebel/link/link_8/sensor/depth_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/oakd_link/rgb_camera/camera_info"
  gz_topic_name: "/world/tomato_field/model/igus_rebel/link/oakd_rgb_camera_frame/sensor/rgb_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS  
- ros_topic_name: "/oakd_link/rgb_camera/image"
  gz_topic_name: "/world/tomato_field/model/igus_rebel/link/oakd_rgb_camera_frame/sensor/rgb_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/oakd_link/pointcloud/points"
  gz_topic_name: "/world/tomato_field/model/igus_rebel/link/link_8/sensor/pointcloud/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS