zig_zag_planning:
  joint_1: 0.0
  joint_2: -40.0
  joint_3: 90.0
  joint_4: 0.0
  joint_5: 40.0
  joint_6: 0.0

nbv_planning:
  joint_1: 0.0
  joint_2: -40.0
  joint_3: 90.0
  joint_4: 0.0
  joint_5: 40.0
  joint_6: 0.0