# This file contains 8 planning waypoints that create a square trajectory with a narrow exploration area

pose_1:
  joint_1: -64.0
  joint_2: -8.0
  joint_3: 51.0
  joint_4: 70.0
  joint_5: 72.0
  joint_6: -40.0

pose_2:
  joint_1: -64.0
  joint_2: -32.0
  joint_3: 123.0
  joint_4: 91.0
  joint_5: 63.0
  joint_6: -92.0

pose_3:
  joint_1: 64.0
  joint_2: -31.0
  joint_3: 122.0
  joint_4: -90.0
  joint_5: 65.0
  joint_6: 92.0

pose_4:
  joint_1: 64.0
  joint_2: -7.0
  joint_3: 51.0
  joint_4: -71.0
  joint_5: 73.0
  joint_6: 41.0
