# This file contains 8 planning waypoints that create a zig zag trajectory with a narrow exploration area

pose_1:
  joint_1: -65.0
  joint_2: 19.0
  joint_3: 1.0
  joint_4: 66.0
  joint_5: 82.0
  joint_6: -18.0

pose_2:
  joint_1: 64.0
  joint_2: -7.0
  joint_3: 50.0
  joint_4: -70.0
  joint_5: 73.0
  joint_6: 40.0

pose_3:
  joint_1: -65.0
  joint_2: -14.0
  joint_3: 66.0
  joint_4: 74.0
  joint_5: 70.0
  joint_6: -49.0

pose_4:
  joint_1: 64.0
  joint_2: -23.0
  joint_3: 87.0
  joint_4: -78.0
  joint_5: 68.0
  joint_6: 61.0

pose_5:
  joint_1: -65.0
  joint_2: -26.0
  joint_3: 96.0
  joint_4: 81.0
  joint_5: 66.0
  joint_6: -68.0

pose_6:
  joint_1: 64.0
  joint_2: -31.0
  joint_3: 113.0
  joint_4: -86.0
  joint_5: 65.0
  joint_6: 81.0

pose_7:
  joint_1: -65.0
  joint_2: -30.0
  joint_3: 118.0
  joint_4: 89.0
  joint_5: 65.0
  joint_6: -87.0

pose_8:
  joint_1: 65.0
  joint_2: -30.0
  joint_3: 133.0
  joint_4: -96.0
  joint_5: 66.0
  joint_6: 105.0